classes: {
    api: {
      style: {
        stroke-width: 0
        fill: "#44C7B1"
        shadow: true
        border-radius: 5
      }
    }
    app: {
      style: {
        fill: "Maroon"
      }
    }
    storage: {
      style: {
        fill: "Orange"
      }
    }
    models: {
      style: {
        fill: "Red"
      }
    }
    database: {
      style: {
        fill: "#c52dc5"
      }
    }
    server
    container: {
      style: {
        fill: "Green"
      }
    }
    agent: {
      style: {
        fill: "#44C7B1"
      }
    }
    docs: {
      style: {
        fill: "Yellow"
      }
    }
  }