user_request

server: Rocky Linux 8 GPU Server {
    nginx: |md nginx docker\
        80:80\
        443:443#| {
    }
    heimdall: Heimdall docker\n81:80\n444:443
    supabase {
        studio: Supabase Studio\n3000:3000
        kong: Kong Reverse Proxy\n8000:8000\n8443:8443
        db: Supabase Postgres\n5432:5432
        postgrest: Postgrest\n3000
        realtime: Supabase Realtime
        gotrue: Supabase Auth
        storage: Supabase Storage\n5000
        edge-functions: Supabase Edge Functions
        imgproxy: Imgproxy\n8080
    }
}