...@classes.d2

direction: right

nih {
  label: NIH Internal
  style: {
    font-size: 100
  }
  posit: Posit Connect {
    icon: ../images/logos/posit-connect-logo.svg
    label.near: outside-top-center
    shiny: ToxPipe Shiny Interface {
      shape: image
      icon: ../images/logos/shiny-hex.png
    }
    orchistrator: ToxPipe \nOrchistrator Agent
    apps: Shiny User Applications {
      shape: image
      icon: ../images/logos/shiny-hex.png
    }
    flask: ToxPipe API {
      shape: image
      icon: ../images/logos/fastapi-logo.png
    }
    flask -> orchistrator: Forwards requests
    shiny -> flask <- apps: Uses API
    flask -> _._.azure.flask: Forwards requests

    orchistrator -> _.biowulf
    orchistrator -> _.storage
  }

  user -> posit.shiny: Explores ToxPipe Data

  user -> posit.apps
  user: Users/Developers {
    icon: ../images/logos/user.svg
    shape: image
  }
  storage: Storage {
    class: storage
    models: Model Storage {
      class: models
      icon: ../images/matrix.svg
      shape: image
    }
  }

  biowulf: BioWulf {
    icon: https://hpc.nih.gov/images/BIOWULF_LOGO
    training: Model Finetuning
    style.3d: false
    style.shadow: true
    style.multiple: false
    style.fill: "#0324ab"
    link: Overview.BioWulf
  }
}

azure: {
  direction: right
  label: Azure Cloud
  label.near: outside-top-center
  style: {
    font-size: 100
  }
  flask: ToxPipe API {
    class: container
  }
  toxpipe: ToxPipe {
    style: {
      font-size: 70
    }
    link: Overview.ToxPipe Azure
  }
  openaiApi: Azure OpenAI API {
    class: api
    shape: image
    icon: ../images/logos/openai-logos/SVGs/openai-lockup.svg
  }
  chembiotox: ChemBioToxDB {
    class: database
    shape: image
    icon: https://icons.terrastruct.com/dev/postgresql-words.svg
  }
  milvus: Vector DB {
    shape: image
    icon: ../images/logos/milvus-logo.jpg
  }
  storage: Storage {
    class: storage
    documents: Documents {
      shape: image
      icon: ../images/documents-vector.svg
    }
    models: Models {
      class: models
    }
  }
  toxpipe -> openaiApi: Queries GPT-4 and GPT-3.5
  flask -> toxpipe: Routes requests

  toxpipe -> storage

  toxpipe -> chembiotox
  toxpipe -> milvus
}

internet {
  label: Internet
  style: {
    font-size: 100
  }
  pubmed: "" {
    class: api
    icon: ../images/logos/pubmed-logo.png
    shape: image
  }
  comptox: Comptox Dashboard {
    class: api
    icon: ../images/logos/epa-logo.png
    shape: image
    link: https://comptox.epa.gov/dashboard/
  }
  google: "" {
    icon: ../images/logos/google-logo.png
    shape: image
  }
  pubchem: "" {
    class: api
    icon: ../images/logos/pubchem-logo.png
    shape: image
  }
}

azure -> internet

# Example of a layer using imports for cleaner syntax
# layers: {
#   serviceB: @serviceB.d2
# }