...@classes.d2

direction: right

nih {
  label: NIH Internal
  style: {
    font-size: 100
  }
  posit: "" {
    shape: image
    icon: ../images/logos/posit-connect-logo.svg
  }
  user: Users/Developers {
    icon: ../images/logos/user.svg
    shape: image
  }
  storage: Storage {
    class: storage
    models: Model Storage {
      class: models
      icon: ../images/matrix.svg
      shape: image
    }
  }
  chembiotox: ChemBioToxDB {
    class: database
    shape: image
    icon: https://icons.terrastruct.com/dev/postgresql-words.svg
  }
  biowulf: "" {
    icon: https://hpc.nih.gov/images/BIOWULF_LOGO
    style.3d: false
    style.shadow: true
    style.multiple: false
    style.fill: "#232b5f"

    training: Model Finetuning {
      style.font-color: "#ffffff"
      shape: image
      icon: ../images/logos/fine_tuning.png
    }
  }
  gpuBox: GPU Server {
    toxpipe: ToxPipe {
      style: {
        font-size: 70
      }
    }
  }
}

azure: {
  direction: right
  label: Azure Cloud
  label.near: outside-top-center
  style: {
    font-size: 100
  }
  openaiApi: "" {
    class: api
    shape: image
    icon: ../images/logos/openai-logos/SVGs/openai-lockup.svg
  }
  cosmosDB: Azure Cosmos DB {
    shape: image
    icon: ../images/logos/azure_cosmosdb.png
  }
  storage: Storage {
    class: storage

    documents: User-uplodaded\ndocuments {
      shape: image
      icon: ../images/documents-vector.svg
    }

    ntpReports: NTP Reports {
      shape: image
      icon: ../images/technical_reports.jpg
    }

    models: Large Language Models {
      shape: image
      icon: ../images/logos/ai_model.png
    }

    pmc: "PMC Open Access" {
      shape: image
      icon: ../images/logos/pmc_long.png
    }
  }
}

internet {
  label: Internet
  style: {
    font-size: 100
  }
  pubmed: "" {
    class: api
    icon: ../images/logos/pubmed-logo.png
    shape: image
  }
  comptox: Comptox Dashboard {
    class: api
    icon: ../images/logos/epa-logo.png
    shape: image
    link: https://comptox.epa.gov/dashboard/
  }
  google: "" {
    icon: ../images/logos/google-logo.png
    shape: image
  }
  pubchem: "" {
    class: api
    icon: ../images/logos/pubchem-logo.png
    shape: image
  }
}

# Example of a layer using imports for cleaner syntax
# layers: {
#   serviceB: @serviceB.d2
# }