aws: "Amazon Web Services" {
  icon: ../images/logos/aws.svg
  bedrock: AWS Bedrock {
    style: {
      font-size: 79
    }
    icon: ../images/logos/amazon_bedrock.svg
    icon.near: "outside-top-left"
    claude: Anthropic/nClaude Models {
      direction: down
      
      opus: Claude 2 Opus {
        shape: image
        icon: ../images/logos/anthropic_opus.svg
      }

      sonnet: Claude 2 Sonnet {
        shape: image
        icon: ../images/logos/anthropic_sonnet.svg
      }

      haiku: Claude 2 Haiku {
        shape: image
        icon: ../images/logos/anthropic_haiku.svg
      }

      claude20: Claude 2.1 {
        shape: image
        icon: ../images/logos/anthropic_opus.svg
        style.fill: "#c55c52"
      }

      claudeInstant: Claude Instant {
        shape: image
        icon: ../images/logos/anthropic_opus.svg
        style.fill: "#c55c52"
      }
    }

    mistral: Mistral AI Models {
      icon: ../images/logos/mistral_ai.svg
      icon.near: "outside-top-left"

      mistralLarge: Mistral Large {
        class: llm
        shape: image
        icon: ../images/logos/mistral_ai_icon.svg
      }

      mistral6bInstruct: Mistral 7B Instruct {
        class: llm
        shape: image
        icon: ../images/logos/mistral_ai_icon.svg
      }

      mistral7x7bInstruct: Mistral 8x7B Instruct {
        class: llm
        shape: image
        icon: ../images/logos/mistral_ai_icon.svg
      }
    }
  }
}