  # biowulf: "" {
  #   icon: https://hpc.nih.gov/images/BIOWULF_LOGO
  #   style.3d: false
  #   style.shadow: true
  #   style.multiple: false
  #   style.fill: "#232b5f"

  #   training: Model Finetuning {
  #     style.font-color: "#ffffff"
  #     # shape: image
  #     # icon: ../images/logos/fine_tuning.png
  #   }
  # }