# https://ntpdev.niehs.nih.gov/restricted/styleguide/

classes: {
    api: {
      style: {
        stroke-width: 0
        fill: "#44C7B1"
        shadow: true
        border-radius: 5
      }
    }
    app: {
      style: {
        fill: "Maroon"
      }
    }
    storage: {
      style: {
        fill: "#f26522" # NTP Orange
      }
    }
    models: {
      style: {
        fill: "#cd0000" # NTP Red
      }
    }
    database: {
      style: {
        fill: "#c52dc5"
      }
    }
    server: {
      style: {
        fill: "#527f24" # NIEHS Green
      }
    }
    container: {
      style: {
        fill: "Green"
      }
    }
    agent: {
      style: {
        fill: "#44C7B1"
      }
    }
    docs: {
      style: {
        fill: "Yellow"
      }
    }
  }