internet {
  label: Internet

  pubmed: "" {
    class: api
    icon: ../images/logos/pubmed-logo.png
    shape: image
  }
  comptox: "Comptox\nDashboard" {
    class: api
    icon: ../images/logos/epa-logo.png
    shape: image
    link: https://comptox.epa.gov/dashboard/
  }
  google: "" {
    icon: ../images/logos/google-logo.png
    shape: image
  }
  pubchem: "" {
    class: api
    icon: ../images/logos/pubchem-logo.png
    shape: image
  }
  semanticScholar: "" {
    class: api
    shape: image
    icon: ../images/logos/semantic_scholar_logo.png
  }
}