# This syntax imports and expands a diagram from another file
...@classes.d2

title: |md
  # ToxPipe Architecture Overview
| { near: top-center }

niehs: NIEHS Internal {
  toxpipeRequest: ToxPipe http(s) request{ 
    description: |md http(s)://toxpipe.niehs.nih.gov |
  }
  server: Rocky Linux 8 GPU Server {
    nginx: nginx docker\n80:80\n443:443 {
    }
    heimdall: {
      shape: square
      tooltip: |md Heimdall is a
        dashboard that allows for nice
        links to other sites. Being used
        as a landing page for now.| 
    }
    supabase {
        studio: Supabase Studio\n3000:3000
        kong: Kong Reverse Proxy\n8000:8000\n8443:8443
        db: Supabase Postgres\n5432:5432
        postgrest: Postgrest\n3000
        realtime: Supabase Realtime
        gotrue: Supabase Auth
        storage: Supabase Storage\n5000
        edge-functions: Supabase Edge Functions
        imgproxy: Imgproxy\n8080
        kong -> db
        kong -> realtime
        kong -> gotrue
        kong -> storage
        kong -> edge-functions
        kong -> imgproxy
        kong -> postgrest
    }
    dialoqbase: Dialoqbas {
      description: |md Dialoquebase is an experimental\
        frontend that allows for document uploads\
        web scraping, and uses React|
    }
    agixt: AGiXT {
      description: |md AGiXT is a web application\
        that allows for the creation of\
        autonomous agents and management\
        of their settings and data\
        that also includes an API|
    }
    nginx -> supabase.studio
    nginx -> supabase.kong: |md location ~ ^/rest/v1/(.*)$\
      location ~ ^/realtime/v1/(.*)$\
      location ~ ^/auth/v1/(.*)$|
    nginx -> dialoqbase
    nginx -> agixt
    nginx -> heimdall

    dialoqbase -> _._.azure.openai.gpt35
    dialoqbase -> _._.azure.openai.embeddings
  }
  toxpipeRequest -> server.nginx
}

azure: Azure {
  # test {
  #   shape: image
  #   icon: ../images/logos/openai-logos/SVGs/openai-lockup.svg
  #   label: ""
  # }
  openai: OpenAI API Endpoint {
    gpt35: GPT-3.5 Turbo
    embeddings: Embeddings model
  }
}
# Example of a layer using imports for cleaner syntax
# layers: {
#   serviceB: @serviceB.d2
# }