map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

upstream supabase {
    server supabase-studio:3000;
}

upstream kong {
    server supabase-kong:8000;
}

upstream agixt2 {
    server agixt:8501;
}

upstream agixt {
    server agixt:7437;
}

# upstream dialoqbase {
#     server dialoqbase:3000;
# }

server {
    listen              443 ssl http2;
    listen              [::]:443 ssl http2;
    server_name         toxpipe.niehs.nih.gov;
    root                /var/www/toxpipe.niehs.nih.gov/public;

    # SSL
    ssl_certificate     /etc/nginx/toxpipe_niehs_nih_gov_chain.crt;
    ssl_certificate_key /etc/nginx/toxpipe_niehs_nih_gov.key;

    # security
    include             nginxconfig.io/security.conf;

    # logging
    access_log          /var/log/nginx/access.log combined buffer=512k flush=1m;
    error_log           /var/log/nginx/error.log debug;

    # REST
    location ~ ^/rest/v1/(.*)$ {
        proxy_set_header Host $host;
        proxy_pass http://kong;
        proxy_redirect off;
    }

    # AUTH
    location ~ ^/auth/v1/(.*)$ {
        proxy_set_header Host $host;
        proxy_pass http://kong;
        proxy_redirect off;
    }

    # REALTIME
    location ~ ^/realtime/v1/(.*)$ {
        proxy_redirect off;
        proxy_pass http://kong;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
    }

    # AGiXT
    location / {
        proxy_set_header Host $host;
        proxy_pass http://agixt;
        proxy_redirect off;
    }

    # Dialoqbase
    # location / {
    #     proxy_set_header Host $host;
    #     proxy_pass http://dialoqbase;
    #     proxy_redirect off;
    # }

    # #STUDIO
    # location /dbadmin {
    #     return 301 $scheme://$host/dbadmin/;
    # }

    # location ~ ^/dbadmin/(.*)$ {
    #     proxy_set_header Host $host;
    #     proxy_pass http://supabase;
    #     proxy_redirect off;
    #     proxy_set_header Upgrade $http_upgrade;
    # }

    # Heimdall Landing Page
    # location / {
    #     include                 nginxconfig.io/proxy.conf;
    #     include                 nginxconfig.io/resolver.conf;
    #     proxy_set_header X-Forwarded-Proto https;
    #     proxy_pass http://heimdall;
    # }
    # Trying alternate Heimdall config
    # location / {
    #     include                 nginxconfig.io/proxy.conf;
    #     include                 nginxconfig.io/resolver.conf;
    #     set                     $upstream_app heimdall;
    #     set                     $upstream_proto https;
    #     proxy_set_header        Host $host;
    #     proxy_pass              $upstream_proto://$upstream_app;
    # }
}

# subdomains redirect
server {
    listen              443 ssl http2;
    listen              [::]:443 ssl http2;
    server_name         *.toxpipe.niehs.nih.gov;

    # SSL
    ssl_certificate     /etc/nginx/toxpipe_niehs_nih_gov.crt;
    ssl_certificate_key /etc/nginx/toxpipe_niehs_nih_gov.key;
    return              301 https://toxpipe.niehs.nih.gov$request_uri;
}

# HTTP redirect
server {
    listen      80;
    listen      [::]:80;
    server_name .toxpipe.niehs.nih.gov;
    return      301 https://toxpipe.niehs.nih.gov$request_uri;
}